version: "3" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  db: # 서비스 명
    image: mysql # 사용할 이미지
    container_name: devwon-mysql # 컨테이너 이름 설정
    restart: unless-stopped
    user: "1000:50" # 컨테이너 권한 설정
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: "1290"  # MYSQL 패스워드 설정 옵션
      MYSQL_USER: kakaopay
      MYSQL_PASSWORD: kakaopay
      MYSQL_DATABASE: kakaopay
      TZ: UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-use-native-aio=0
    volumes:
      - ./mysqldata:/var/lib/mysql # -v 옵션 (디렉토리 마운트 설정)